# Generated by Django 2.2.6 on 2020-03-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-date', 'currency']},
        ),
        migrations.AlterModelOptions(
            name='productprices',
            options={'ordering': ['-date', 'product']},
        ),
        migrations.AlterModelOptions(
            name='stockprices',
            options={'ordering': ['-date', 'companyID']},
        ),
    ]
