# Generated by Django 2.2.6 on 2020-03-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20200307_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=40)),
                ('old', models.FloatField()),
                ('new', models.FloatField()),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Trade')),
            ],
        ),
    ]
